include $(HOME)/Makefile_templates/Makefile

#funcion_muestreo_small.png:	funcion_muestreo.pdf
#			convert -resize 50% funcion_muestreo.png funcion_muestreo_small.png
#TMPs += funcion_muestreo_small.png

#default:	$(TMPs)
